name: yris-bot

include:
  - path: ../ai_chat/docker-compose.yml

services:
  python-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VARIANT: ".14-slim"
    environment:
      OPTIONS: ""
    volumes:
      - ..:/lichess-bot/config
    depends_on:
      - llama
    restart: unless-stopped
