name: yris-bot

services:
#  llama:
#    image: ghcr.io/ggml-org/llama.cpp:server
#    restart: unless-stopped
#    platform: ${PLATFORM:-}
#    env_file:
#      - .env
#    ports:
#      - "5555:8080"
#    volumes:
#      - hf-cache:/root/.cache   # persists downloads between restarts
#    command:
#      [
#        "-hf", "ggml-org/gemma-3-1b-it-GGUF:Q4_K_M",
#        "--host", "0.0.0.0",
#        "--port", "8080",
#        "-c", "2048",
#        "-fa", "on"
#      ]

  python-bot:
    platform: ${PLATFORM:-}
    build:
      context: .
      dockerfile: custom.Dockerfile
      args:
        VARIANT: ".13"
    restart: unless-stopped
    environment:
      OPTIONS: ""
    env_file:
      - .env # .env file inside the /docker/ folder, used to specify the PLATFORM variable if needed to be overridden
    volumes:
      - ../config.yml:/lichess-bot/config.yml
      - ../engines:/lichess-bot/engines
#    depends_on:
#      - llama

#volumes:
#  hf-cache:
